# This file was generated by GoReleaser. DO NOT EDIT.
cask "hal" do
  name "hal"
  desc "HAL 9000 - Local HashiCorp Infrastructure Orchestrator"
  homepage "https://github.com/hashimiche/hal"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hal"

  on_macos do
    on_intel do
      url "https://github.com/hashimiche/hal/releases/download/v#{version}/hal_Darwin_amd64.tar.gz"
      sha256 "b1f9722f92ad1cc20b5837285ca82227ca5c0cadc28b0b85d7e40a5b179891f1"
    end
    on_arm do
      url "https://github.com/hashimiche/hal/releases/download/v#{version}/hal_Darwin_arm64.tar.gz"
      sha256 "21677e0fc675cf2a5e4b5cefd2fb631a9b1826a8ffade442f4b72e8fadff9d9e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hashimiche/hal/releases/download/v#{version}/hal_Linux_amd64.tar.gz"
      sha256 "c47a28d46cf980c1749bea382d1efc8da99c8f6507a9fbd3229a06a79643d98d"
    end
    on_arm do
      url "https://github.com/hashimiche/hal/releases/download/v#{version}/hal_Linux_arm64.tar.gz"
      sha256 "977848c1ab05a1183ea327b494d2510de04b9283ec4ec5e786eac6058e7027b3"
    end
  end

  # No zap stanza required
end
